# Codecov configuration for PantryPilot
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        # Make default project check informational (won't block PRs)
        # The combined coverage can fluctuate when frontend tests are added
        informational: true
      backend:
        # Backend-specific coverage target
        flags:
          - backend
        threshold: 1%
      frontend:
        # Frontend-specific coverage target
        flags:
          - frontend
        threshold: 1%
    patch:
      default:
        # Disable patch coverage requirement - infrastructure/deployment code
        # is often environment-specific and validated through integration tests
        # rather than unit tests
        informational: true

# Ignore infrastructure and configuration files from coverage
ignore:
  - "apps/backend/src/main.py"  # App initialization with env-specific middleware
  - "apps/backend/src/dependencies/db.py"  # Database connection setup
  - "apps/backend/src/core/config.py"  # Configuration loading
  - "**/__init__.py"
  - "**/tests/**"
